# fly.toml app configuration file generated for redwoodjs-partner-badges on 2023-08-31T16:54:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redwoodjs-partner-badges"
primary_region = "iad"

[build]

[deploy]
  release_command = ".fly/release.sh"

[env]
  PORT = "8910"
  REDWOOD_DISABLE_TELEMETRY = "1"

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
