name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-lint-test:
    name: 🏗 Build, lint, test
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - uses: redwoodjs/project-ci-action@main
        with:
          node-version: '18'
          project-directory: './'
          run-lint: 'yes'
          yarn3-cache: 'yes'
